# Generated by Django 6.0 on 2026-03-02 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('lat_center', models.FloatField(verbose_name='Latitude')),
                ('lng_center', models.FloatField(verbose_name='Longitude')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VegetationDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('ndvi_value', models.FloatField(help_text='NDVI de -1 à 1')),
                ('density_class', models.CharField(choices=[('sparse', 'Éparse'), ('moderate', 'Modérée'), ('dense', 'Dense'), ('very_dense', 'Très dense')], max_length=20)),
                ('coverage_percent', models.FloatField(help_text='% de couverture végétale')),
                ('change_vs_previous', models.FloatField(default=0, help_text='Variation NDVI vs analyse précédente')),
                ('geojson', models.JSONField(default=dict, help_text='GeoJSON Polygon de la zone')),
                ('last_analyzed', models.DateTimeField(default=django.utils.timezone.now)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation', to='dashboard.zone')),
            ],
            options={
                'verbose_name': 'Végétation',
                'verbose_name_plural': 'Végétations',
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('status', models.CharField(choices=[('bon', 'Bon état'), ('degrade', 'Dégradé'), ('critique', 'Critique'), ('ferme', 'Fermé')], default='bon', max_length=20)),
                ('condition_score', models.FloatField(help_text='Score de 0 (mauvais) à 100 (excellent)')),
                ('geojson', models.JSONField(default=dict, help_text='GeoJSON LineString du tracé')),
                ('last_analyzed', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='dashboard.zone')),
            ],
            options={
                'verbose_name': 'Segment routier',
                'verbose_name_plural': 'Segments routiers',
                'ordering': ['condition_score'],
            },
        ),
        migrations.CreateModel(
            name='FloodRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('risk_level', models.CharField(choices=[('faible', 'Faible'), ('modere', 'Modéré'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='faible', max_length=20)),
                ('risk_score', models.FloatField(help_text='Score de risque 0-100')),
                ('area_km2', models.FloatField(help_text='Surface en km²')),
                ('rainfall_mm', models.FloatField(default=0, help_text='Précipitations récentes en mm')),
                ('geojson', models.JSONField(default=dict, help_text='GeoJSON Polygon de la zone')),
                ('last_analyzed', models.DateTimeField(default=django.utils.timezone.now)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flood_risks', to='dashboard.zone')),
            ],
            options={
                'verbose_name': "Zone d'inondation",
                'verbose_name_plural': "Zones d'inondation",
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger'), ('critical', 'Critique')], max_length=20)),
                ('category', models.CharField(choices=[('road', 'Route'), ('flood', 'Inondation'), ('vegetation', 'Végétation'), ('system', 'Système')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.zone')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
