# Generated by Django 5.1.15 on 2026-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='surface_type',
            field=models.CharField(blank=True, choices=[('bitume', 'Bitume'), ('terre', 'Terre'), ('pave', 'Pavé'), ('gravier', 'Gravier'), ('autre', 'Autre')], default='bitume', max_length=20, verbose_name='Type de surface'),
        ),
    ]
