# Generated by Django 5.1.15 on 2026-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_surface_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodrisk',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Identifiant unique OSM — clé de mise à jour lors des imports', null=True, verbose_name='ID OpenStreetMap'),
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Identifiant unique OSM — clé de mise à jour lors des imports', null=True, verbose_name='ID OpenStreetMap'),
        ),
        migrations.AddField(
            model_name='vegetationdensity',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Identifiant unique OSM — clé de mise à jour lors des imports', null=True, verbose_name='ID OpenStreetMap'),
        ),
        migrations.AddIndex(
            model_name='floodrisk',
            index=models.Index(fields=['zone', 'osm_id'], name='flood_zone_osm_idx'),
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['zone', 'osm_id'], name='road_zone_osm_idx'),
        ),
        migrations.AddIndex(
            model_name='vegetationdensity',
            index=models.Index(fields=['zone', 'osm_id'], name='veg_zone_osm_idx'),
        ),
        migrations.AddConstraint(
            model_name='floodrisk',
            constraint=models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('zone', 'osm_id'), name='unique_flood_osm_id_per_zone'),
        ),
        migrations.AddConstraint(
            model_name='roadsegment',
            constraint=models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('zone', 'osm_id'), name='unique_road_osm_id_per_zone'),
        ),
        migrations.AddConstraint(
            model_name='vegetationdensity',
            constraint=models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('zone', 'osm_id'), name='unique_veg_osm_id_per_zone'),
        ),
    ]
