# Generated by Django 5.1.15 on 2026-03-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_floodrisk_osm_id_roadsegment_osm_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSection',
            fields=[
            ],
            options={
                'verbose_name': 'Section routière',
                'verbose_name_plural': 'Sections routières',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.roadsegment',),
        ),
    ]
