# Generated by Django 5.1.15 on 2026-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alert_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='is_strategic',
            field=models.BooleanField(db_index=True, default=False, help_text='True pour motorway/trunk/primary/secondary — filtre indexé pour la vue décisionnelle (remplace un regex coûteux sur `notes`).', verbose_name='Axe structurant'),
        ),
    ]
