# Generated by Django 5.1.15 on 2026-06-22 15:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_divisions', '0003_add_district_to_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Frontière du département (HDX ADM2).', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sousprefecture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Polygone (union des communes membres ou frontière officielle).', null=True, srid=4326)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='admin_divisions.departement', verbose_name='Département')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='admin_divisions.district', verbose_name='District')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='admin_divisions.region', verbose_name='Région')),
                ('sous_prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='admin_divisions.sousprefecture', verbose_name='Sous-préfecture')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='admin_divisions.ville', verbose_name='Ville'),
        ),
    ]
